kakao:
  api:
    key: ${KAKAO_API_KEY}
    base-url: https://dapi.kakao.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET_ID}

jwt:
  secret: ${JWT_SECRET}
