kakao:
  api:
    key: your-kakao-api-key-here
    base-url: https://dapi.kakao.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret

jwt:
  secret: jwt-secret
  expiration: 900000
  refresh-secret: jwt-refresh-secret
  refresh-expiration: 604800000

aws:
  s3:
    bucket: bucket-name
    uri: bucket-uri
    directory: bucket-directory
