name: Add My IP And Port to Inbound Rules

on:
  workflow_dispatch:
    inputs:
      port:
        description: '허용할 포트 (예: 3306)'
        required: true
        default: '3306'

jobs:
  authorize-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Get My Public IP
        id: ip
        run: |
            MY_IP=$(curl -s https://checkip.amazonaws.com | tr -d '\n')
            echo "MY_IP=$MY_IP" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authorize IP on Security Group
        run: |
          PORT=${{ github.event.inputs.port }}
          IP=${{ env.MY_IP }}
          if [[ "$PORT" != "3306" && "$PORT" != "80" ]]; then
            echo "❌ 허용되지 않은 포트입니다. 3306 또는 80만 가능합니다."
            exit 1
          fi

          EXISTS=$(aws ec2 describe-security-groups \
            --group-ids "${{ secrets.AWS_SG_ID }}" \
            --query "SecurityGroups[0].IpPermissions[?ToPort==\`${PORT}\`].IpRanges[?CidrIp=='${IP}/32']" \
            --output text)

          if [[ -n "$EXISTS" ]]; then
            echo "✅ 이미 IP와 ${PORT} 규칙이 존재하여 등록을 생략합니다."
            exit 0
          fi

          echo "✅ 입력한 IP와 ${PORT} 포트로 인바운드 등록합니다."

          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp \
            --port "${PORT}" \
            --cidr "${IP}/32" > /dev/null 2>&1
