name: Add My IP And Port to Inbound Rules

on:
  workflow_dispatch:
    inputs:
      ip:
        description: '본인의 현재 IP 주소 (예: 1.2.3.4)'
        required: true
      port:
        description: '허용할 포트 (예: 3306)'
        required: true
        default: '3306'

jobs:
  authorize-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authorize IP on Security Group
        run: |
          PORT=${{ github.event.inputs.port }}
          IP=${{ github.event.inputs.ip }}
          if [[ "$PORT" != "3306" && "$PORT" != "80" ]]; then
            echo "❌ 허용되지 않은 포트입니다. 3306 또는 80만 가능합니다."
            exit 1
          fi

          if ! [[ "$IP" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
            echo "❌ 올바른 IPv4 형식이 아닙니다. 예: 123.45.67.89"
            exit 1
          fi

          OCTETS=(${IP//./ })
          for octet in "${OCTETS[@]}"; do
            if ((octet < 0 || octet > 255)); then
              echo "❌ IP 주소의 각 자리는 0~255 사이여야 합니다."
              exit 1
            fi
          done

          echo "✅ 입력한 IP와 ${PORT} 포트로 인바운드 등록합니다."

          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SG_ID }} \
            --protocol tcp \
            --port ${PORT} \
            --cidr ${IP}/32
            --output none
